#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
$: << File.join(File.dirname(File.expand_path(__FILE__)) , 'lib')
require 'rubygems'
require 'bundler'
Bundler.setup
require 'twtr2wp'
Twtr2wp::Twtr2wp.new.run
